### ISSUE TITLE
Crashed when tap `Weather` when first enter. Could not be reproduced.

### ISSUE THREAD

**Issue by qiuncheng** [Desgard/Calendouer-iOS#42]

**Comment by SeaHub** [comment]
According to symbol table provided by Bugly.
Perhaps this crashing is caused by Alamofire.
We can't reappear locally and lack of enough information to fix it.
If you find the way of reappearing the crash, please tell us, 3Q.

![Crash](http://on9ydhp18.bkt.clouddn.com/pics/20170820002105_vHoFFH_Crash.jpeg)
